# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ";hc"
    replace: "好的老师"
  - trigger: ";email"
    replace: "ihaixiu@tom.com"
  - trigger: ";semail"
    replace: "guoxy@zut.edu.cn"

  # Markdown
  - trigger: ";mword"
    replace: "`$|$`"
  - trigger: ";mlink"
    replace: "[]($|$)"

  # Obisdian
  - trigger: ";olink"
    replace: "![$|$]"
    # 搭配annotation快速输入
  - trigger: ";opdf"
    replace: "---\nannotation-target: $|$\n---"
    # 进阶版annatation输入，支持直接输入名称
  - trigger: ";oipdf"
    replace: "---\nannotation-target: {{fpdf.ppdf}}.pdf\n---"
    vars:
      - name: fpdf
        type: form
        params:
          layout: |-
            pdf文件名: {{ppdf}}
          fields:
            ppdf:
              multiline: false

  # code

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"